#pragma once

#define ENCODER_RESOLUTION 4

#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT

#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 60000

#define DEBOUNCE 5